hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

name: default
architecture:
  type: combined
  mod: False
  mlp: False
  pose: True
  use_head_yaw_pitch: False
  split_gaze:
    n_layers: [2,2,2]
    output_features: 100
  head:
    n_layers: 2
    hidden_features: 560 # 2*(213+15) + 4 + 100

train_options:
  lr: 0.000662002
  wd: 0.1
  sgd: False
  angular_loss: False
  # scheduling: 0
  dropout_split: 0.0
  dropout: 0.0
  dropout_head: 0.0
  no_bn: False
  batch_size: 128
  # single_step_lr:
  #   start_after: 3
  #   factor: 0.1
  max_epochs: 20
  lr_scheduling_updates_per_epoch: 1
  swa:
    enabled: True
    start: 0.75 # can be a proportion of max epoch like 0.75 or a specific epoch like 12
    scheduler_lr_factor: 0.1
    # lr: 0.0000662002
  person_loss: False



run_options:
  test: True
  val: True
  num_workers: -1 # means same as cpu count
  faze_split: False
  leave_out: 10
  leave_out_val: 1
  augment:
    enabled: False
    color_jitter: True
    random_affine: True
    grayscale: True
    random_affine_degrees_variation: 0.0
    random_affine_translate: 0.1
    random_affine_scale_variation: 0.1
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_hue: 0.05
  memory: False
  preprocess: False
  load_split: 
  # split: 0.8


dataset_path: ~/datasets/hdf5/

defaults:
  - dataset: mpiig_static
