defaults:
  - dataset: mpiig
          
      

name: mpiig_trained
# start_lr: 1e-4
# end_lr_factor: 1e-3
architecture:
  type: combined
  mod: False
  mlp: True
  pose: True
  use_head_yaw_pitch: False
  split_gaze:
    n_layers: [2,2,2]
    n_layers_mod: 0 # used to set the n_layers array to [n_layers_mod, n_layers_mod, n_layers_mod] if not 0
    output_features: 50
  head:
    dense: False
    n_layers: 2
    hidden_features: 50

train_options:
  lr: 3e-6
  wd: 0.1
  sgd: False
  angular_loss: false
  # scheduling: 0
  dropout: 0.0
  dropout_gaussian: False
  dropout_split: 0.0
  dropout_split_gaussian: False
  dropout_head: 0.1
  no_bn: False
  batch_size: 64
  # single_step_lr:
  #   start_after: 5
  #   factor: 0.1
  cyclic_lr:
    per_epoch: True
    max_lr: 3e-5
    period: 3
    mode: exp_range
  # step_lr:
  #   step_size: 3
  #   factor: 0.3
  max_epochs: 15
  lr_scheduling_updates_per_epoch: 1
  swa:
    enabled: False
    start: 0.75 # can be a proportion of max epoch like 0.75 or a specific epoch like 12
    scheduler_lr_factor: 0.01
    # lr: 0.0000662002
    disable_scheduling: True
  person_loss: False
  bn_splits: 0



run_options:
  test: True
  val: True
  num_workers: 16 # means same as cpu count
  faze_split: False
  leave_out:
    idx_val: 14
    idx_test: 14
  augment:
    enabled: True
    color_jitter: True
    random_affine: False
    grayscale: True
    random_affine_degrees_variation: 2.0
    random_affine_translate: 0.3
    random_affine_scale_variation: 0.2
    color_jitter_brightness: 0.4
    color_jitter_contrast: 0.4
    color_jitter_saturation: 0.4
    color_jitter_hue: 0.1
    dev_head_yaw_pitch: 0.0
  memory: False
  preprocess: False
  load_split: False
  # split: 0.8
  save: True
  new_norm: False


dataset_path: ~/datasets/hdf5/
  
