defaults:
  - dataset: mpiig_static
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: cmaes
  

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: mpiig_leave_out_9_2
    storage: mysql+pymysql://cedric:cLm41194!@168.138.71.83:3306/optuna
    n_trials: 40
    n_jobs: 1

    search_space:
      # start_lr:
      #   type: float
      #   low: 1e-7
      #   high: 1e-3
      #   log: True
      # end_lr_factor:
      #   type: categorical
      #   choices: [1.0, 1e-1, 1e-2, 1e-3]
      # architecture.head.dense:
      #   type: categorical
      #   choices: [False, True]
      # train_options.lr:
      #   type: float
      #   low: 1e-7
      #   high: 1e-3
      #   log: True
      train_options.wd:
          type: categorical
          choices: [10.0, 1.0, 0.1, 0.0]
      train_options.dropout:
          type: categorical
          choices: [0.1, 0.0]
      train_options.dropout_head:
          type: categorical
          choices: [0.5, 0.1, 0.0]
      train_options.single_step_lr.start_after:
        type: int
        low: 2
        high: 10
      # train_options.single_step_lr.factor: ${hydra.sweeper.search_space.end_lr_factor}
      # train_options.swa.scheduler_lr_factor: ${hydra.sweeper.search_space.end_lr_factor}
      train_options.single_step_lr.factor:
        type: categorical
        choices: [1.0, 1e-1, 1e-2, 1e-3]
      train_options.swa.scheduler_lr_factor:
        type: categorical
        choices: [1.0, 1e-1, 1e-2, 1e-3]

      run_options.augment.random_affine_degrees_variation:
        type: categorical
        choices: [0.0, 1.0, 3.0]
      run_options.augment.random_affine_translate:
        type: categorical
        choices: [0.0, 0.1, 0.2]
      run_options.augment.random_affine_scale_variation:
        type: categorical
        choices: [0.0, 0.1, 0.2]
      

      
      # run_options.augment.color_jitter:
      #   type: categorical
      #   choices: [False, True]
      # run_options.augment.random_affine:
      #   type: categorical
      #   choices: [False, True]
      # run_options.augment.grayscale:
      #   type: categorical
      #   choices: [False, True]
          
      

name: mpiig_leave_out_9_optuna_sweep2
# start_lr: 1e-4
# end_lr_factor: 1e-3
architecture:
  type: combined
  mod: False
  mlp: True
  pose: True
  use_head_yaw_pitch: False
  split_gaze:
    n_layers: [2,2,2]
    output_features: 50
  head:
    dense: False
    n_layers: 2
    hidden_features: 50

train_options:
  lr: 1e-5
  wd: 0.1
  sgd: False
  angular_loss: False
  # scheduling: 0
  dropout: 0.0
  dropout_head: 0.0
  no_bn: False
  batch_size: 128
  single_step_lr:
    start_after: 3
    factor: 0.1
  max_epochs: 20
  lr_scheduling_updates_per_epoch: 1
  swa:
    enabled: True
    start: 0.75 # can be a proportion of max epoch like 0.75 or a specific epoch like 12
    scheduler_lr_factor: 0.1
    # lr: 0.0000662002



run_options:
  test: True
  val: False
  num_workers: -1 # means same as cpu count
  faze_split: False
  leave_out: 9
  leave_out_val: 1
  augment:
    enabled: True
    color_jitter: True
    random_affine: True
    grayscale: True
    random_affine_degrees_variation: 0.0
    random_affine_translate: 0.1
    random_affine_scale_variation: 0.1
  memory: False
  preprocess: False
  load_split: 
  # split: 0.8


dataset_path: ~/datasets/hdf5/
  
